<a href="https://colab.research.google.com/github/akki0894/FeatureEngineering/blob/main/Feature_Engineering_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [15]:
df = pd.read_csv("Churn_Modelling.csv")

In [16]:
df.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

Our Y variable is "Exited". The X's are CreditScore,Geography,Gender,Age,Tenure,Balnace,NumofProducts,HasCrCard,IsActiveMember,Estimated Salary

In [17]:
X = df.iloc[:,3:13].values
type(X)
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [18]:
y = df.iloc[:,13].values
type(y)
y

array([1, 0, 1, ..., 1, 1, 0])

In [19]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder = LabelEncoder()

X[:,2] = labelencoder.fit_transform(X[:,2])
X

X[:,1] = labelencoder.fit_transform(X[:,1])
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [20]:
from sklearn.compose import ColumnTransformer 

ct = ColumnTransformer([("Country", OneHotEncoder(), [1])], remainder = 'passthrough')

X = ct.fit_transform(X)
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [21]:
X = pd.DataFrame(X, columns = ["X1","X2","X3","Credit Score","Gender","Age","Tenure","Balance","NumofProducts","HasCrCard","IsActiveMember",	"EstimatedSalary"])

In [22]:
X

X1 X2 X3  ... HasCrCard IsActiveMember EstimatedSalary
0     1  0  0  ...         1              1          101349
1     0  0  1  ...         0              1          112543
2     1  0  0  ...         1              0          113932
3     1  0  0  ...         0              0         93826.6
4     0  0  1  ...         1              1         79084.1
...  .. .. ..  ...       ...            ...             ...
9995  1  0  0  ...         1              0         96270.6
9996  1  0  0  ...         1              1          101700
9997  1  0  0  ...         0              1         42085.6
9998  0  1  0  ...         1              0         92888.5
9999  1  0  0  ...         1              0         38190.8

[10000 rows x 12 columns]